### ISSUE TITLE
How I use custom browser-sync plugin ?

### ISSUE THREAD

**Issue by retyui** [itgalaxy/browser-sync-dev-hot-webpack-plugin#27]
Update api for use custom plugins:
example:
https://github.com/shakyShane/html-injector

**Comment by evilebottnawi** [comment]
@retyui out of scope plugin, you can fork plugin or write new plugin based on this

**Comment by retyui** [comment]
@evilebottnawi The documentation has found how to connect plug-ins via options:
```js
plugins: [
	{
		module: "bs-html-injector",
		options: {
			files: [/* pwd() + */ "./views/templates/**/*.tpl"]
		}
	}
]
```

But a found small bag : 
https://github.com/itgalaxy/browser-sync-dev-hot-webpack-plugin/blob/master/src/BrowserSyncDevHotWebpackPlugin.js#L96

If the user uses an option for the proxy as a string.
That with merge he will pererate middleware

```js
new BrowserSyncHotPlugin({
    browserSync: {
        proxy: 'http://myphp.backend/'
    },
})
```

**Comment by retyui** [comment]
https://github.com/itgalaxy/browser-sync-dev-hot-webpack-plugin/pull/28
