### ISSUE TITLE
Don't uses callback function

### ISSUE THREAD

**Issue by retyui** [itgalaxy/browser-sync-dev-hot-webpack-plugin#31]
In option you add `callback` property.
But not called here https://github.com/itgalaxy/browser-sync-dev-hot-webpack-plugin/blob/master/src/BrowserSyncDevHotWebpackPlugin.js#L173 
This is mistake?

You wanted to write the following:
`this.options.callback.call(this, bs)`

**Comment by evilebottnawi** [comment]
@retyui Seems bug, PR welcome

**Comment by retyui** [comment]
Well done! 
https://github.com/itgalaxy/browser-sync-dev-hot-webpack-plugin/pull/32
